---
apiVersion: v1
kind: Namespace
metadata:
  name:  acmecorp-developer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: acmecorp-developer
  name: acmecorp-developer-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: acmecorp-developer-app
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acmecorp-developer-app
    spec:
      containers:
      - image: supipi/developerapi:main
        imagePullPolicy: Always
        name: acmecorp-developer-app
        ports:
        - containerPort: 8088
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: acmecorp-developer
  name: acmecorp-developer-service
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: acmecorp-developer-app
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: acmecorp-developer
  name: management-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: management-app
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: management-app
    spec:
      containers:
      - image: supipi/managementapi:main
        imagePullPolicy: Always
        name: management-app
        ports:
        - containerPort: 8089
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: acmecorp-developer
  name: management-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: management-app
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: acmecorp-developer
  name: monitoring-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-app
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monitoring-app
    spec:
      containers:
      - image: supipi/monitoringapi:main
        imagePullPolicy: Always
        name: monitoring-app
        ports:
        - containerPort: 8090
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: acmecorp-developer
  name: monitoring-service
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: monitoring-app
  type: LoadBalancer
status:
  loadBalancer: {}